# Numpy
NumPy is a Python library that performs numerical calculations. It is generally used for working with arrays.


Advantages of numpy arrays-

1.Numpy uses less memory and storage space, which is the main advantage.

2.NumPy offers better performance in terms of execution speed.          

In [1]:
import numpy as np

# comparing time taken  by list  vs numpy

In [2]:
from time import process_time

In [3]:
li=[i for i in range(200000)]
start_time=process_time()
li=[i+3 for i in li]
end_time=process_time()
print(end_time - start_time)

0.03125


In [4]:
np_array=np.array([i for i in range(200000)])
start_time=process_time()
np_array +=3
end_time=process_time()
print(end_time - start_time)

0.0


# Numpy Array

In [5]:
li=[1,2,3,4,5,6]
print(li)
type(li)

[1, 2, 3, 4, 5, 6]


list

In [6]:
np_array=np.array([1,2,3,4,5,6])
print(np_array)
type(np_array)    #nd=n dimention array

[1 2 3 4 5 6]


numpy.ndarray

In [7]:
#creating 1 d array
a=np.array([7,9,6,9,3])
print(a)
a.shape

[7 9 6 9 3]


(5,)

In [8]:
#creating 2 d array
a=np.array([(7,9,6,9,3),(8,2,4,8,0)])
print(a)
a.shape

[[7 9 6 9 3]
 [8 2 4 8 0]]


(2, 5)

In [9]:
b=np.array([(7,99,6,9,3),(8,2,4,8,0)],dtype=float)
print(b)

[[ 7. 99.  6.  9.  3.]
 [ 8.  2.  4.  8.  0.]]


In [10]:
#initial placeholders in numpy arrays
x=np.zeros((4,5),dtype=int)
print(x)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [11]:
y=np.ones((3,8),dtype=int)
print(y)

[[1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]]


In [12]:
#array of particular values
z=np.full((7,7),6)
print(z)

[[6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6]]


In [13]:
#create an identity matrix(n*n matrix with all diagonal elements as 1 and remaining as 0)
a=np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [14]:
#numpy array with random values(between 0 to 1 bydefault)
a=np.random.random((4,4))
print(a)

[[0.71820115 0.55041663 0.01347781 0.66516596]
 [0.84327778 0.28979679 0.89257978 0.77284297]
 [0.11359784 0.84347436 0.70648204 0.24980123]
 [0.1400364  0.0661479  0.36766988 0.49012564]]


In [15]:
#numpy array with random values(within specific range)
b=np.random.randint(120,170,(4,4))
print(b)

[[159 122 132 121]
 [152 122 152 150]
 [123 122 147 130]
 [122 158 151 164]]


In [16]:
#array of evenly spaced values(specifying how many values are required(5 in this example))
a=np.linspace(0,20,5)   # 0 to 20 is the range 
print(a)

[ 0.  5. 10. 15. 20.]


In [17]:
#array of evenly spaced values(specifying how many steps or skips required(5 here))
a=np.arange(0,40,5)     #0 to 40 is the range
print(a)

[ 0  5 10 15 20 25 30 35]


In [18]:
#converting a list to numpy array
li=[40,80,33,5,8,99]
type(li)
a=np.asarray(li)
print(a)
type(a)


[40 80 33  5  8 99]


numpy.ndarray

# Analysing a numpy array

In [19]:
x=np.random.randint(10,50,(5,5))
print(x)

[[36 18 11 46 11]
 [24 15 42 43 23]
 [21 16 25 49 39]
 [14 33 41 38 19]
 [39 12 46 33 10]]


In [20]:
x.shape

(5, 5)

In [21]:
x.ndim

2

In [22]:
#no. of elements in array
x.size

25

In [23]:
#checking datatype of values in array
print(x.dtype)

int32


# Mathematical operations on numpy array

In [24]:
li1=[1,2,3,4,5,5]
li2=[10,20,30,4,5,50]
print(li1+li2)   #will just concatinate/join

[1, 2, 3, 4, 5, 5, 10, 20, 30, 4, 5, 50]


In [25]:
a=np.array([1,2,3,4,5,5])
b=np.array([10,20,30,4,5,55])
print(a+b)

[11 22 33  8 10 60]


In [26]:
print(a-b)

[ -9 -18 -27   0   0 -50]


In [27]:
print(b/a)

[10. 10. 10.  1.  1. 11.]


In [28]:
print(a*b)

[ 10  40  90  16  25 275]


In [29]:
#OR by using functions
sum=np.add(a,b)
print(sum)
sub=np.subtract(a,b)
print(sub)
mult=np.multiply(a,b)
print(mult)
div=np.divide(b,a)
print(div)

[11 22 33  8 10 60]
[ -9 -18 -27   0   0 -50]
[ 10  40  90  16  25 275]
[10. 10. 10.  1.  1. 11.]


# Array manipulation

In [30]:
a=np.random.randint(10,100,(2,5))
print(a)

[[33 55 16 87 96]
 [99 63 34 26 79]]


In [31]:
#transpose
trans=np.transpose(a)
print(trans)


[[33 99]
 [55 63]
 [16 34]
 [87 26]
 [96 79]]


In [32]:
#or by 
trans1=a.T
print(trans1)

[[33 99]
 [55 63]
 [16 34]
 [87 26]
 [96 79]]
